package com.esei.uvigo.futbolapp;

public class TeamActivity {
    /* LISTAR TODOS LOS JUGADORES CON SUS CORRESPONDIENTES POSICIONES, SI CLICKAS EN UN JUGADOR TE PODRÍA
    LLEVAR A SUS ESTADÍSTICAS DONDE PODRÍAS SACAR UN INFORME DE ESE JUGADOR, ADEMÁS HACEN FALTA MENUS
    PARA FILTRAR JUGADORES POR POSICIÓN Y NOMBRE, ES DECIR, UNA LISTVIEW DE JUGADORES, UN MENU PARA
    FILTRAR, QEU APAREZCA EL NOMBRE DEL EQUIPO ARRIBA*/

}
